In [1]:
import torch

In [2]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [11]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [12]:
print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[ 0.3177]])


In [4]:
## Calculate the output of this network using the weights and bias tensors
linear_combination = (features*weights).sum()
print("Linear Combination")
print(linear_combination)
out_put = activation(linear_combination + bias)
print("Neuron Output")
print(out_put)
#print(torch.mm(features , weights))

Linear Combination
tensor(-1.9796)
Neuron Output
tensor([[ 0.1595]])


In [17]:
activation (torch.mm(features,weights.view(5,1)).add(bias))

tensor([[ 0.1595]])

In [6]:
two_by_three_matrix = features = torch.randn((2,3))
print(two_by_three_matrix)
print(two_by_three_matrix.shape)

tensor([[ 0.1328,  0.1373,  0.2405],
        [ 1.3955,  1.3470,  2.4382]])
torch.Size([2, 3])
